<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\URL;

class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if($this->app->environment('production')) {
            URL::forceScheme('https');
        }

        // Optional: Force HTTPS in all URLs generated by the asset() helper
        if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') {
            \Illuminate\Support\Facades\URL::forceScheme('https');
        }
    }
}